controller: gloo

params:
  fusion_threshold_mb: 64
  cycle_time_ms: 5
  cache_capacity: 1024
  hierarchical_allreduce: false
  hierarchical_allgather: false

autotune:
  enabled: false
  log_file: 'horovod_autotune_log.txt'
  warmup_samples: 3
  batches_per_sample: 10
  bayes_opt_max_samples: 20
  gaussian_process_noise: 0.8

timeline:
  enabled: false
  filename: 'horovod_timeline.json'
  mark_cycles: false

stall_check:
  enabled: true
  warning_time_seconds: 60
  shutdown_time_seconds: 0

library_options:
  mpi_threads_disabled: false
  num_nccl_streams: 1
  mlsl_bgt_affinity: 0
