#syntax=docker/dockerfile:1.2
# run this with DOCKER_BUILDKIT=1 docker build ...
# or with COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build ...
# use BUILDKIT_PROGRESS=plain for plain log output

ARG CUDA_DOCKER_VERSION=10.0-devel-ubuntu20.04
FROM nvidia/cuda:${CUDA_DOCKER_VERSION}

# Arguments for the build. CUDA_DOCKER_VERSION needs to be repeated because
# the first usage only applies to the FROM tag.
ARG CUDA_DOCKER_VERSION=10.0-devel-ubuntu20.04
ARG CUDNN_VERSION=7.6.0.64-1+cuda10.0
ARG NCCL_VERSION_OVERRIDE=2.4.7-1+cuda10.0
ARG MPI_KIND=OpenMPI
ARG PYTHON_VERSION=3.6
ARG GPP_VERSION=7
ARG TENSORFLOW_PACKAGE=tensorflow-gpu==1.15.0
ARG KERAS_PACKAGE=keras==2.2.4
ARG PYTORCH_PACKAGE=torch==1.2.0
ARG PYTORCH_LIGHTNING_PACKAGE=pytorch_lightning==0.7.6
ARG TORCHVISION_PACKAGE=torchvision==0.4.0
ARG MXNET_PACKAGE=mxnet-cu100==1.5.0
ARG PYSPARK_PACKAGE=pyspark==2.4.7
# if SPARK_PACKAGE is set, installs Spark into /spark from the tgz archive
# if SPARK_PACKAGE is a preview version, installs PySpark from the tgz archive
# see https://archive.apache.org/dist/spark/ for available packages, version must match PYSPARK_PACKAGE
ARG SPARK_PACKAGE=spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
ARG HOROVOD_BUILD_FLAGS="HOROVOD_GPU_OPERATIONS=NCCL"
ARG HOROVOD_MIXED_INSTALL=0

# to avoid interaction with apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

# Make Ubuntu not delete downloaded packages
RUN rm -f /etc/apt/apt.conf.d/docker-clean

# Prepare to install specific g++ versions
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update -qq && apt-get install -y --no-install-recommends software-properties-common
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    add-apt-repository ppa:ubuntu-toolchain-r/test

# Install essential packages.
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    CUDNN_MAJOR=$(cut -d '.' -f 1 <<< "${CUDNN_VERSION}"); \
    apt-get update -qq && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        wget \
        ca-certificates \
        openssh-client \
        openssh-server \
        git \
        build-essential \
        g++-${GPP_VERSION} \
        moreutils \
        libcudnn${CUDNN_MAJOR}=${CUDNN_VERSION} \
        libnccl2=${NCCL_VERSION_OVERRIDE} \
        libnccl-dev=${NCCL_VERSION_OVERRIDE}

# setup ssh service
RUN ssh-keygen -f /root/.ssh/id_rsa -q -N ''
RUN cp -v /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

# Install Python.
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update -qq && apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-distutils
RUN ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python
RUN ln -s -f /usr/bin/python${PYTHON_VERSION} /usr/bin/python${PYTHON_VERSION/%.*/}
# cannot cache get-pip.py as it may change size
RUN --mount=type=cache,target=/root/.cache/pip \
    wget --progress=dot:mega https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py; \
    python /tmp/get-pip.py; \
    rm -f /tmp/get-pip.py

# pinning pip to 21.0.0 as 22.0.0 cannot fetch pytorch packages from html linl
# https://github.com/pytorch/pytorch/issues/72045
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -U --force pip~=21.0.0 setuptools requests pytest mock pytest-forked parameterized

# Install recent CMake.
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --no-cache-dir -U cmake~=3.13.0

# Add launch helper scripts
RUN echo "env SPARK_HOME=/spark SPARK_DRIVER_MEM=512m PYSPARK_PYTHON=/usr/bin/python${PYTHON_VERSION} PYSPARK_DRIVER_PYTHON=/usr/bin/python${PYTHON_VERSION} \"\$@\"" > /spark_env.sh
RUN echo /spark_env.sh pytest -v --capture=no --continue-on-collection-errors --junit-xml=/artifacts/junit.\$1.\${HOROVOD_RANK:-\${OMPI_COMM_WORLD_RANK:-\${PMI_RANK}}}.\$2.xml \${@:2} > /pytest.sh
RUN echo /spark_env.sh pytest -v --capture=no --continue-on-collection-errors --junit-xml=/artifacts/junit.\$1.standalone.\$2.xml --forked \${@:2} > /pytest_standalone.sh
RUN chmod a+x /spark_env.sh
RUN chmod a+x /pytest.sh
RUN chmod a+x /pytest_standalone.sh

# Install Spark stand-alone cluster.
RUN --mount=type=cache,target=/wget \
    if [[ -n ${SPARK_PACKAGE} ]]; then \
        mkdir -p /wget/$(dirname "${SPARK_PACKAGE}"); \
        wget -c --progress=dot:giga "https://www.apache.org/dyn/closer.lua/spark/${SPARK_PACKAGE}?action=download" -O /wget/${SPARK_PACKAGE}; \
        tar -xzC /tmp -f /wget/${SPARK_PACKAGE}; \
        archive=$(basename "${SPARK_PACKAGE}") bash -c "mv -v /tmp/\${archive/%.tgz/} /spark"; \
    fi

# Install PySpark.
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update -qq && apt install -y openjdk-8-jdk-headless
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    --mount=type=cache,target=/root/.cache/pip \
    if [[ ${SPARK_PACKAGE} != *"-preview"* ]]; then \
        pip install ${PYSPARK_PACKAGE}; \
    else \
        apt-get update -qq && apt-get install pandoc; \
        pip install pypandoc; \
        (cd /spark/python && python setup.py sdist && pip install dist/pyspark-*.tar.gz && rm dist/pyspark-*); \
    fi

# Install Ray.
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install ray==1.7.0

# Install MPI.
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt,sharing=locked \
    --mount=type=cache,target=/wget \
    if [[ ${MPI_KIND} == "OpenMPI" ]]; then \
        wget -c --progress=dot:mega -O /wget/openmpi-3.0.0-bin.tar.gz https://github.com/horovod/horovod/files/1596799/openmpi-3.0.0-bin.tar.gz && \
            cd /usr/local && tar -zxf /wget/openmpi-3.0.0-bin.tar.gz && ldconfig && \
            echo "mpirun -allow-run-as-root -np 2 -H localhost:2 -bind-to none -map-by slot -mca mpi_abort_print_stack 1" > /mpirun_command; \
    elif [[ ${MPI_KIND} == "MPICH" ]]; then \
        apt-get update -qq && apt-get install -y mpich && \
            echo "mpirun -np 2" > /mpirun_command; \
    fi

# Set default NCCL parameters
RUN echo NCCL_DEBUG=INFO >> /etc/nccl.conf

# Install mpi4py.
# This requires SETUPTOOLS_USE_DISTUTILS=stdlib as with setuptools>=60.1.0 installing mpi4py broke
# https://github.com/mpi4py/mpi4py/issues/157#issuecomment-1001022274
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${MPI_KIND} != "None" ]]; then \
        SETUPTOOLS_USE_DISTUTILS=stdlib pip install mpi4py; \
    fi

# Install TensorFlow and Keras (releases).
# Pin h5py only for tensorflow<2.5: https://github.com/h5py/h5py/issues/1732
# Pin scipy!=1.4.0: https://github.com/scipy/scipy/issues/11237
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${TENSORFLOW_PACKAGE} != "tf-nightly-gpu" ]]; then \
        pip install ${TENSORFLOW_PACKAGE}; \
        if [[ ${KERAS_PACKAGE} != "None" ]]; then \
            if [[ ${TENSORFLOW_PACKAGE} == tensorflow*==1.* ]] || [[ ${TENSORFLOW_PACKAGE} == tensorflow*==2.[012345].* ]]; then \
                h5py="h5py<3"; \
            fi; \
            pip uninstall -y keras-nightly; \
            pip install ${KERAS_PACKAGE} ${h5py:-} "scipy!=1.4.0" "pandas<1.1.0"; \
        fi; \
        mkdir -p ~/.keras; \
        ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs; \
        python -c "import tensorflow as tf; tf.keras.datasets.mnist.load_data()"; \
        ldconfig; \
    fi

# Install PyTorch (releases).
# Pin Pillow<7.0 for torchvision < 0.5.0: https://github.com/pytorch/vision/issues/1718
# Pin Pillow!=8.3.0 for torchvision: https://github.com/pytorch/vision/issues/4146
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${PYTORCH_PACKAGE} != "torch-nightly-cu"* ]]; then \
        pip install ${PYTORCH_PACKAGE} ${TORCHVISION_PACKAGE} -f https://download.pytorch.org/whl/${PYTORCH_PACKAGE/*+/}/torch_stable.html; \
        if [[ "${TORCHVISION_PACKAGE/%+*/}" == torchvision==0.[1234].* ]]; then \
            pip install "Pillow<7.0" --no-deps; \
        else \
            pip install "Pillow!=8.3.0" --no-deps; \
        fi; \
    fi
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install ${PYTORCH_LIGHTNING_PACKAGE}

# Install MXNet (releases).
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${MXNET_PACKAGE} != "mxnet-nightly-cu"* ]]; then \
        pip install ${MXNET_PACKAGE} ; \
    fi

# Prefetch Spark MNIST dataset.
RUN --mount=type=cache,target=/wget \
    mkdir -p /data /work; \
    wget -c --progress=dot:mega https://horovod-datasets.s3.amazonaws.com/mnist.bz2 -O /wget/mnist.bz2; \
    cp /wget/mnist.bz2 /data/

# Prefetch Spark Rossmann dataset.
RUN --mount=type=cache,target=/wget \
    mkdir -p /data /work; \
    wget -c --progress=dot:mega https://horovod-datasets.s3.amazonaws.com/rossmann.tgz -O /wget/rossmann.tgz; \
    tar -xzC /data -f /wget/rossmann.tgz

# Prefetch PyTorch datasets.
RUN --mount=type=cache,target=/wget \
    wget -c --progress=dot:mega https://horovod-datasets.s3.amazonaws.com/pytorch_datasets.tgz -O /wget/pytorch_datasets.tgz; \
    tar -xzC /data -f /wget/pytorch_datasets.tgz

### END OF CACHE ###
COPY . /horovod

# Install nightly packages here so they do not get cached

# Install TensorFlow and Keras (nightly).
# Pin scipy!=1.4.0: https://github.com/scipy/scipy/issues/11237
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${TENSORFLOW_PACKAGE} == "tf-nightly-gpu" ]]; then \
        pip install ${TENSORFLOW_PACKAGE}; \
        if [[ ${KERAS_PACKAGE} != "None" ]]; then \
            pip uninstall -y keras-nightly; \
            pip install ${KERAS_PACKAGE} "scipy!=1.4.0" "pandas<1.1.0"; \
        fi; \
        mkdir -p ~/.keras; \
        ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs; \
        python -c "import tensorflow as tf; tf.keras.datasets.mnist.load_data()"; \
        ldconfig; \
    fi

# Install PyTorch (nightly).
# Pin Pillow!=8.3.0 for torchvision: https://github.com/pytorch/vision/issues/4146
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${PYTORCH_PACKAGE} == "torch-nightly-cu"* ]]; then \
        pip install --pre torch ${TORCHVISION_PACKAGE} -f https://download.pytorch.org/whl/nightly/${PYTORCH_PACKAGE/#torch-nightly-/}/torch_nightly.html; \
        pip install "Pillow!=8.3.0" --no-deps; \
    fi

# Install MXNet (nightly).
RUN --mount=type=cache,target=/root/.cache/pip \
    if [[ ${MXNET_PACKAGE} == "mxnet-nightly-cu"* ]]; then \
        pip install --pre ${MXNET_PACKAGE/-nightly/} -f https://dist.mxnet.io/python/${MXNET_PACKAGE/#mxnet-nightly-/}; \
    fi

# Install Horovod.
RUN --mount=type=cache,target=/root/.cache/pip \
    cd /horovod && \
    python setup.py sdist && \
    ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    bash -c "${HOROVOD_BUILD_FLAGS} HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_MXNET=1 pip install -v $(ls /horovod/dist/horovod-*.tar.gz)[spark,ray]" && \
    ldconfig

# Show the effective python package version to easily spot version differences
RUN pip freeze | sort

# Hack for compatibility of MNIST example with TensorFlow 1.1.0.
RUN if [[ ${TENSORFLOW_PACKAGE} == "tensorflow-gpu==1.1.0" ]]; then \
        sed -i "s/from tensorflow import keras/from tensorflow.contrib import keras/" /horovod/examples/tensorflow/tensorflow_mnist.py; \
    fi

# Hack TensorFlow MNIST example to be smaller.
RUN sed -i "s/last_step=20000/last_step=100/" /horovod/examples/tensorflow/tensorflow_mnist.py

# Hack TensorFlow Eager MNIST example to be smaller.
RUN sed -i "s/dataset.take(20000/dataset.take(100/" /horovod/examples/tensorflow/tensorflow_mnist_eager.py

# Hack TensorFlow 2.0 example to be smaller.
RUN sed -i "s/dataset.take(10000/dataset.take(100/" /horovod/examples/tensorflow2/tensorflow2_mnist.py

# Hack Keras MNIST advanced example to be smaller.
RUN sed -i "s/'--epochs', type=int, default=24,/'--epochs', type=int, default=9,/" /horovod/examples/keras/keras_mnist_advanced.py

# Hack TensorFlow 2.0 Keras MNIST advanced example to be smaller.
RUN sed -i "s/epochs=24/epochs=9/" /horovod/examples/tensorflow2/tensorflow2_keras_mnist.py

# Hack PyTorch MNIST example to be smaller.
RUN sed -i "s/'--epochs', type=int, default=10,/'--epochs', type=int, default=2,/" /horovod/examples/pytorch/pytorch_mnist.py

# Hack Keras Spark Rossmann Run example to be smaller.
RUN sed -i "s/x = Dense(1000,/x = Dense(100,/g" /horovod/examples/spark/keras/keras_spark_rossmann_run.py
RUN sed -i "s/x = Dense(500,/x = Dense(50,/g" /horovod/examples/spark/keras/keras_spark_rossmann_run.py

# Hack Keras Spark Rossmann Estimator example to be smaller.
RUN sed -i "s/x = Dense(1000,/x = Dense(100,/g" /horovod/examples/spark/keras/keras_spark_rossmann_estimator.py
RUN sed -i "s/x = Dense(500,/x = Dense(50,/g" /horovod/examples/spark/keras/keras_spark_rossmann_estimator.py

# Export HOROVOD_MIXED_INSTALL
ENV HOROVOD_MIXED_INSTALL=${HOROVOD_MIXED_INSTALL}
