# keep rest of this workflow in-sync with buildkite_unit_tests_master.yaml
name: Unit Tests (Branch)
on:
  # pushing to non-master branches, ignore non-code changes
  push:
    branches-ignore: master
    tags-ignore: "**"
    # keep paths-ignore in-sync with .buildkite/gen-pipeline.sh
    # buildkite does not run tests when there are no changes in paths other then these
    paths-ignore:
    - ".buildkite/get_commit_files.py"
    - ".github/**"
    - "docs/"
    - "*.md"
    - "*.rst"

jobs:
  buildkite:
    name: "Buildkite Unit Tests"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'horovod'

    steps:
    - name: Download Buildkite Artifacts
      uses: EnricoMi/download-buildkite-artifact-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        buildkite_token: ${{ secrets.BUILDKITE_TOKEN }}
        output_path: test-results
        log_level: DEBUG
      continue-on-error: true

    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@master
      with:
        check_name: Unit Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: "test-results/**/*.xml"
        log_level: DEBUG
      continue-on-error: true

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: test-results/**/*.xml
